[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Cache-Control = "no-cache, no-store, must-revalidate"
